name: genhop
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - annotated-types=0.6.0
  - anyio=4.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - catalogue=2.0.10
  - certifi=2024.6.2
  - charset-normalizer=2.0.4
  - click=8.1.7
  - cloudpathlib=0.16.0
  - colorama=0.4.6
  - confection=0.1.4
  - cymem=2.0.6
  - cython-blis=0.7.9
  - distro=1.9.0
  - exceptiongroup=1.2.0
  - expat=2.6.2
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.26.0
  - huggingface_hub=0.23.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - jinja2=3.1.4
  - langcodes=3.3.0
  - ld_impl_linux-64=2.38
  - libcxx=14.0.6
  - libcxxabi=14.0.6
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libopenblas=0.3.21
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - llvm-openmp=14.0.6
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - mdurl=0.1.0
  - murmurhash=1.0.7
  - ncurses=6.4
  - nomkl=3.0
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openai=1.25.0
  - openssl=3.0.13
  - packaging=23.2
  - pathy=0.10.3
  - pip=24.0
  - preshed=3.0.6
  - pydantic=1.10.12
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.10.14
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - rich=13.3.5
  - safetensors=0.4.2
  - setuptools=69.5.1
  - shellingham=1.5.0
  - smart_open=5.2.1
  - sniffio=1.3.0
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.45.3
  - srsly=2.4.8
  - tk=8.6.14
  - tqdm=4.66.4
  - typer=0.4.1
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wasabi=0.9.1
  - weasel=0.3.4
  - wheel=0.43.0
  - xz=5.4.6
  - yaml=0.2.5
  - zipp=3.17.0
  - zlib=1.2.13
  - pip:
      - spacy==3.5
      - tokenizers==0.19.1
      - torch==2.3.1
      - transformers==4.41.2
